# Generated by Django 5.0.3 on 2024-03-30 11:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
