# Generated by Django 5.0.3 on 2024-03-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text",
            field=models.TextField(),
        ),
    ]
